### ISSUE TITLE
[Suggestion] 1.16.5  Configurable max level

### ISSUE THREAD

**Issue by GoldenTotem** [MC-U-Team/Attack-Speed-Enchantment#19]
### Detailed description of the feature

I didn't find the config file of the mod, so I think this mod needs a config file.
I suggest that the max level of enchantment can be configured, you can choose a number between 1 to 10.
What's more, you can choose whether axe can use this enchantment or not.

### Verify feature request

- [X] I have checked that this is not a duplicate feature request and the feature does not yet exist in the latest version

**Comment by Wubzzz1337** [comment]
Would be a great option for Balancing!
Hopefully also for 1.19.2
