### ISSUE TITLE
[1.20.1, Fabric] Game crashes

### ISSUE THREAD

**Issue by Kai-Denzel-Jane** [MC-U-Team/Attack-Speed-Enchantment#36]
### Bug description and reproduction steps

The game crashes error is something about refMap not loaded.

Its marked as 1.19.X for used minecraft version because theres no 1.20.X

I also attached log

### Log files and Screenshots

[latest.log](https://github.com/MC-U-Team/Attack-Speed-Enchantment/files/11847346/latest.log)

### Used minecraft version

1.19.x

### Used forge version

Fabric 0.14.21 (1.20.1)

### Used mod version

1.3.0.18

**Comment by HyCraftHD** [comment]
Fixed in these versions: 
![image](https://github.com/MC-U-Team/Attack-Speed-Enchantment/assets/7681220/99c31db0-a706-4b6b-b59f-3b89c428e4a4)
